### ISSUE TITLE
High-level To-do List

### ISSUE THREAD

**Issue by bclyons12** [ProjectTorreyPines/FRESCO.jl#1]
- [x] Inversion of Grad-Shafranov operator
- [x] Inner loop to iterate on the nonlinear dependence of Jt on the flux (Picard iterations with relaxation)
- [x] Outer loop on the boundary value of the flux
- [ ] Vertical stability feedback
- [x] Shape control
- [ ] GSevolve-like linearization for rapid time-evolution
